同步源码

diff --git a/trunk/build_firmware b/trunk/build_firmware
--- a/trunk/build_firmware
+++ b/trunk/build_firmware
@@ -1,4 +1,41 @@
-#!/bin/sh
+#!/bin/bash
+
+if [ -z "$1" ] || [ "$EUID" != 0 ]; then
+	echo "Please run 'fakeroot $0 PRODUCT_NAME' to start build (see 'configs/templates/')"
+	echo "For Windows Subsystem for Linux(WSL), use 'fakeroot-tcp' instead of 'fakeroot', or run with sudo"
+	exit 1
+fi
+
+if [ ! -f configs/templates/$1.config ] ; then
+	echo "configs/templates/$1.config not found!"
+	exit 1
+fi
+
+cp -f configs/templates/$1.config .config
+sed -i 's/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=y/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n/g' .config
+sed -i 's/CONFIG_FIRMWARE_INCLUDE_MENTOHUST=y/CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n/g' .config
+sed -i 's/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=y/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n/g' .config
+sed -i 's/CONFIG_FIRMWARE_INCLUDE_SRELAY=y/CONFIG_FIRMWARE_INCLUDE_SRELAY=n/g' .config
+sed -i 's/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=y/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=n/g' .config
+
+##以下为插件增减选项,y为集成,n为不集成,请根据自己路由的FLASH大小选择,切勿超大小,不然固件刷入后会无法启动
+##此插件选项只在本地编译的时候才会生效
+##科学上网##
+echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=n" >> .config #科学上网插件，选择n后全部有关插件都不集成
+echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=n" >> .config #集成v2ray执行文件，如果不集成，会从网上下载下来执行，不影响正常使用
+echo "CONFIG_FIRMWARE_INCLUDE_TROJAN=n" >> .config #集成trojan执行文件，如果不集成，会从网上下载下来执行，不影响正常使用
+echo "CONFIG_FIRMWARE_INCLUDE_SSOBFS=n" >> .config #simple-obfs混淆插件
+##科学上网##
+
+##锐捷认证##
+echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n" >> .config #锐捷认证插件，选择n后全部有关插件都不集成
+echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> .config
+##锐捷认证##
+
+##内网穿透##
+echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=n" >> .config #zerotier ~1.3M
+echo "CONFIG_FIRMWARE_INCLUDE_NPS=n" >> .config #nps ~0.8M
+##内网穿透证##
 
 ROOTDIR=`pwd`
 export ROOTDIR=$ROOTDIR
@@ -6,9 +43,6 @@ export ROOTDIR=$ROOTDIR
 kernel_id="3.4.x"
 kernel_cf=""
 kernel_tf=""
-uclibc_id="uClibc-ng-1.0.32"
-uclibc_cf=""
-uclibc_tf="$ROOTDIR/libc/${uclibc_id}/.config"
 busybox_id="1.24.x"
 busybox_cf="$ROOTDIR/configs/boards/busybox.config"
 busybox_tf="$ROOTDIR/user/busybox/busybox-${busybox_id}/.config"
@@ -32,13 +66,6 @@ func_disable_kernel_param()
 	fi
 }
 
-func_disable_libc_param()
-{
-	if [ -n "`grep \^$1=y $uclibc_tf`" ] ; then
-		sed -i "s/$1=y/\# $1 is not set/" $uclibc_tf
-	fi
-}
-
 func_enable_busybox_param()
 {
 	if [ -n "`grep \^\"\# $1 is not set\" $busybox_tf`" ] ; then
@@ -52,21 +79,14 @@ func_disable_busybox_param()
 		sed -i "s/$1=y/\# $1 is not set/" $busybox_tf
 	fi
 }
-
-if [ ! -f "$ROOTDIR/.config" ] ; then
-	cp -fv "$ROOTDIR/configs/templates/n56u_dlna.config" "$ROOTDIR/.config"
-fi
-
-if [ ! -f "$ROOTDIR/.config" ] ; then
-	echo "Project config file .config not found! Terminate."
-	exit 1
-fi
+. $ROOTDIR/toolchain.inc
+echo "CONFIG_TOOLCHAIN_DIR=${CONFIG_TOOLCHAIN_DIR}" >> .config
 
 # load project root config
 . $ROOTDIR/.config
 
-if [ ! -f "$ROOTDIR/vendors/Ralink/$CONFIG_PRODUCT/config.arch" ] ; then
-	echo "Project product dir ($CONFIG_PRODUCT) not found! Terminate."
+if [ ! -f "$ROOTDIR/vendors/Ralink/config.arch" ] ; then
+	echo "Project product dir not found! Terminate."
 	exit 1
 fi
 
@@ -77,27 +97,19 @@ fi
 
 board_h="$ROOTDIR/configs/boards/$CONFIG_FIRMWARE_PRODUCT_ID/board.h"
 board_mk="$ROOTDIR/configs/boards/$CONFIG_FIRMWARE_PRODUCT_ID/board.mk"
-uclibc_cf="$ROOTDIR/configs/boards/$CONFIG_FIRMWARE_PRODUCT_ID/libc.config"
 kernel_cd="$ROOTDIR/configs/boards/$CONFIG_FIRMWARE_PRODUCT_ID"
 kernel_tf="$ROOTDIR/$CONFIG_LINUXDIR/.config"
 
-if [ "$CONFIG_LINUXDIR" = "linux-3.0.x" ] ; then
-	kernel_id="3.0.x"
-fi
-
 if [ "$CONFIG_FIRMWARE_TYPE_ROOTFS_IN_RAM" = "y" ] ; then
 	kernel_cf="${kernel_cd}/kernel-${kernel_id}.ram.config"
+elif [ -n "$CONFIG_FIRMWARE_KERNEL_CONFIG" ]; then
+	kernel_cf="${kernel_cd}/$CONFIG_FIRMWARE_KERNEL_CONFIG"
 else
 	kernel_cf="${kernel_cd}/kernel-${kernel_id}.config"
 fi
 
 if [ ! -f "$kernel_cf" ] ; then
 	echo "Target kernel config ($kernel_cf) not found! Terminate."
-	exit 1
-fi
-
-if [ ! -f "$uclibc_cf" ] ; then
-	echo "Target uClibc config ($uclibc_cf) not found! Terminate."
 	exit 1
 fi
 
@@ -126,9 +138,8 @@ mkdir -p $ROOTDIR/images
 
 echo --------------------------COPY-CONFIG-----------------------------
 ######################### FOR-ALL-DEVICES #############################
-ln -sf vendors/Ralink/$CONFIG_PRODUCT/config.arch config.arch
+ln -sf vendors/Ralink/config.arch config.arch
 cp -fL "$kernel_cf" "$kernel_tf"
-cp -fL "$uclibc_cf" "$uclibc_tf"
 cp -fL "$busybox_cf" "$busybox_tf"
 cp -fL "$board_mk" "$ROOTDIR/user/shared/board.mk"
 cp -fL "$board_h" "$ROOTDIR/user/shared/include/ralink_board.h"
@@ -145,6 +156,16 @@ rm -rf "$dir_wifi_dst/mt7610"
 rm -rf "$dir_wifi_dst/mt76x2"
 rm -rf "$dir_wifi_dst/mt76x3"
 rm -rf "$dir_wifi_dst/mt7628"
+rm -rf "$dir_wifi_dst/mt7615"
+rm -rf "$dir_wifi_dst/mt7915"
+
+mkdir -p "$dir_wifi_dst/mt76x3"
+cp -f "$dir_wifi_src/rtpci/4.1.X.X/mt76x3/Kconfig" "$dir_wifi_dst/mt76x3/Kconfig"
+mkdir -p "$dir_wifi_dst/mt7615/embedded"
+cp -f "$dir_wifi_src/rtpci/5.0.5.1/mt7615/embedded/Kconfig" "$dir_wifi_dst/mt7615/embedded/Kconfig"
+mkdir -p "$dir_wifi_dst/mt7915/embedded"
+cp -f "$dir_wifi_src/rtpci/7.3.0.1/mt7915/embedded/Kconfig" "$dir_wifi_dst/mt7915/embedded/Kconfig"
+
 if [ -n "$CONFIG_RT2860V2_AP" ] ; then
 	dir_wifi_ver="2.7.X.X"
 	if [ "$CONFIG_RALINK_RT3883" = "y" ] && [ "$CONFIG_FIRMWARE_WIFI5_DRIVER" = "2.4" ] ; then
@@ -212,6 +233,21 @@ if [ -n "$CONFIG_MT7628_AP" ] ; then
 	cp -rfL "$dir_wifi_src/rtsoc/$dir_wifi_ver/mt7628" "$dir_wifi_dst/"
 	cp -rfL "$dir_wifi_src/rtsoc/$dir_wifi_ver/mt7628_ap" "$dir_wifi_dst/"
 fi
+if [ -n "$CONFIG_MT7615_AP" ] ; then
+	dir_wifi_ver="5.0.5.1"
+	if [ "$CONFIG_FIRMWARE_WIFI_DRIVER" = "4.4.2.1" ] || \
+		[ "$CONFIG_FIRMWARE_WIFI2_DRIVER" = "4.4.2.1" ] || \
+		[ "$CONFIG_FIRMWARE_WIFI5_DRIVER" = "4.4.2.1" ]; then
+		dir_wifi_ver="4.4.2.1"
+	fi
+	cp -rfL "$dir_wifi_src/rtpci/$dir_wifi_ver/mt7615" "$dir_wifi_dst/"
+	cp -rfL "$dir_wifi_src/rtpci/$dir_wifi_ver/mt7615_ap" "$dir_wifi_dst/"
+fi
+if [ -n "$CONFIG_MT7915_AP" ] ; then
+	dir_wifi_ver="7.3.0.1"
+	cp -rfL "$dir_wifi_src/rtpci/$dir_wifi_ver/mt7915" "$dir_wifi_dst/"
+	cp -rfL "$dir_wifi_src/rtpci/$dir_wifi_ver/mt7915_ap" "$dir_wifi_dst/"
+fi
 ############################ HWNAT ####################################
 dir_ppe_src="$ROOTDIR/proprietary/rt_ppe"
 dir_ppe_dst="$ROOTDIR/$CONFIG_LINUXDIR/net/nat"
@@ -264,7 +300,6 @@ fi
 if [ "$CONFIG_FIRMWARE_ENABLE_IPV6" != "y" ] ; then
 	func_disable_kernel_param "CONFIG_INET_TUNNEL"
 	func_disable_kernel_param "CONFIG_IPV6"
-	func_disable_libc_param "UCLIBC_HAS_IPV6"
 	func_disable_busybox_param "CONFIG_PING6"
 	func_disable_busybox_param "CONFIG_FEATURE_IPV6"
 	func_disable_busybox_param "CONFIG_FEATURE_PREFER_IPV4_ADDRESS"
@@ -276,36 +311,18 @@ if [ "$CONFIG_FIRMWARE_ENABLE_IPV6" != "y" ] ; then
 	func_enable_busybox_param "CONFIG_FEATURE_IP_LINK"
 	func_enable_busybox_param "CONFIG_FEATURE_IP_ROUTE"
 fi
+#SFE
+if [ "$CONFIG_FIRMWARE_INCLUDE_SFE" = "y" ] ; then
+	func_enable_kernel_param "CONFIG_SHORTCUT_FE"
+	func_enable_kernel_param "CONFIG_NF_CONNTRACK_EVENTS"
+	func_enable_kernel_param "CONFIG_NF_CONNTRACK_CHAIN_EVENTS"
+else
+	func_disable_kernel_param "CONFIG_SHORTCUT_FE"
+	func_disable_kernel_param "CONFIG_NF_CONNTRACK_EVENTS"
+	func_disable_kernel_param "CONFIG_NF_CONNTRACK_CHAIN_EVENTS"
+fi
 ############################# USB #####################################
 if [ "$CONFIG_FIRMWARE_ENABLE_USB" != "y" ] || [ -z "$CONFIG_USB_SUPPORT" ] ; then
-	func_disable_kernel_param "CONFIG_SWAP"
-	func_disable_kernel_param "CONFIG_FAT_FS"
-	func_disable_kernel_param "CONFIG_MSDOS_FS"
-	func_disable_kernel_param "CONFIG_VFAT_FS"
-	func_disable_kernel_param "CONFIG_UFSD_FS"
-	func_disable_kernel_param "CONFIG_EXFAT_FS"
-	func_disable_kernel_param "CONFIG_EXT2_FS"
-	func_disable_kernel_param "CONFIG_EXT3_FS"
-	func_disable_kernel_param "CONFIG_EXT4_FS"
-	func_disable_kernel_param "CONFIG_JBD"
-	func_disable_kernel_param "CONFIG_JBD2"
-	func_disable_kernel_param "CONFIG_XFS_FS"
-	func_disable_kernel_param "CONFIG_FUSE_FS"
-	func_disable_kernel_param "CONFIG_FSCACHE"
-	func_disable_kernel_param "CONFIG_INOTIFY_USER"
-	func_disable_kernel_param "CONFIG_NFSD"
-	func_disable_kernel_param "CONFIG_PARTITION_ADVANCED"
-	func_disable_kernel_param "CONFIG_NLS_CODEPAGE_866"
-	func_disable_kernel_param "CONFIG_NLS_ISO8859_1"
-	func_disable_kernel_param "CONFIG_SCSI"
-	func_disable_kernel_param "CONFIG_SCSI_MOD"
-	func_disable_kernel_param "CONFIG_INPUT"
-	func_disable_kernel_param "CONFIG_USB_SUPPORT"
-	func_disable_kernel_param "CONFIG_HID_SUPPORT"
-	func_disable_kernel_param "CONFIG_MEDIA_SUPPORT"
-	func_disable_kernel_param "CONFIG_CRC16"
-	func_disable_kernel_param "CONFIG_NETFILTER_FP_SMB"
-	func_disable_kernel_param "CONFIG_RT3XXX_EHCI_OHCI"
 	func_disable_busybox_param "CONFIG_FDISK"
 	func_disable_busybox_param "CONFIG_FEATURE_FDISK_WRITABLE"
 	func_disable_busybox_param "CONFIG_FEATURE_FDISK_ADVANCED"
@@ -321,11 +338,6 @@ if [ "$CONFIG_FIRMWARE_ENABLE_USB" != "y" ] || [ -z "$CONFIG_USB_SUPPORT" ] ; th
 	func_disable_busybox_param "CONFIG_FEATURE_VOLUMEID_EXT"
 	func_disable_busybox_param "CONFIG_FEATURE_VOLUMEID_XFS"
 	func_disable_busybox_param "CONFIG_FEATURE_VOLUMEID_LINUXSWAP"
-	if [ "$CONFIG_FIRMWARE_INCLUDE_OPENVPN" != "y" ] ; then
-		func_disable_kernel_param "CONFIG_TUN"
-		func_disable_kernel_param "CONFIG_HOTPLUG"
-	fi
-	CONFIG_FIRMWARE_INCLUDE_NFSD=n
 else
 ############################# UFSD ####################################
 if [ "$CONFIG_FIRMWARE_ENABLE_UFSD" != "y" ] ; then
@@ -374,13 +386,13 @@ if [ "$CONFIG_FIRMWARE_ENABLE_SWAP" != "y" ] ; then
 	func_disable_busybox_param "CONFIG_SWAPONOFF"
 fi
 ############################# NFSD ####################################
-if [ "$CONFIG_FIRMWARE_INCLUDE_NFSD" != "y" ] ; then
-	func_disable_kernel_param "CONFIG_NFSD"
-fi
+# if [ "$CONFIG_FIRMWARE_INCLUDE_NFSD" != "y" ] ; then
+#	func_disable_kernel_param "CONFIG_NFSD"
+# fi
 ############################# UVC #####################################
-if [ "$CONFIG_FIRMWARE_INCLUDE_UVC" != "y" ] ; then
-	func_disable_kernel_param "CONFIG_MEDIA_SUPPORT"
-fi
+#if [ "$CONFIG_FIRMWARE_INCLUDE_UVC" != "y" ] ; then
+#	func_disable_kernel_param "CONFIG_MEDIA_SUPPORT"
+#fi
 ############################# HID #####################################
 if [ "$CONFIG_FIRMWARE_INCLUDE_HID" != "y" ] ; then
 	func_disable_kernel_param "CONFIG_INPUT"
@@ -458,32 +470,36 @@ if [ "$CONFIG_FIRMWARE_INCLUDE_IFB" != "y" ] ; then
 	func_disable_kernel_param "CONFIG_IFB"
 fi
 ############################# NFSC ####################################
-if [ "$CONFIG_FIRMWARE_INCLUDE_NFSC" != "y" ] ; then
-	func_disable_kernel_param "CONFIG_FSCACHE"
-	func_disable_kernel_param "CONFIG_NFS_FS"
-fi
+#if [ "$CONFIG_FIRMWARE_INCLUDE_NFSC" != "y" ] ; then
+#	func_disable_kernel_param "CONFIG_FSCACHE"
+#	func_disable_kernel_param "CONFIG_NFS_FS"
+#fi
 ############################# CIFS ####################################
-if [ "$CONFIG_FIRMWARE_INCLUDE_CIFS" != "y" ] ; then
-	func_disable_kernel_param "CONFIG_CIFS"
-	func_disable_busybox_param "CONFIG_FEATURE_MOUNT_CIFS"
-fi
-if [ "$CONFIG_FIRMWARE_INCLUDE_SMBD" != "y" ] ; then
-	func_disable_kernel_param "CONFIG_NETFILTER_FP_SMB"
-fi
-if [ "$CONFIG_FIRMWARE_INCLUDE_NFSD" != "y" -a "$CONFIG_FIRMWARE_INCLUDE_NFSC" != "y" -a "$CONFIG_FIRMWARE_INCLUDE_CIFS" != "y" ] ; then
-	func_disable_kernel_param "CONFIG_NETWORK_FILESYSTEMS"
-	if [ "$CONFIG_FIRMWARE_ENABLE_USB" != "y" ] || [ -z "$CONFIG_USB_SUPPORT" ] ; then
-		func_disable_kernel_param "CONFIG_NLS"
-		func_disable_kernel_param "CONFIG_LBDAF"
-	fi
-fi
+# if [ "$CONFIG_FIRMWARE_INCLUDE_CIFS" != "y" ] ; then
+# 	func_disable_kernel_param "CONFIG_CIFS"
+# 	func_disable_busybox_param "CONFIG_FEATURE_MOUNT_CIFS"
+# fi
+# if [ "$CONFIG_FIRMWARE_INCLUDE_SMBD" != "y" ] ; then
+# 	func_disable_kernel_param "CONFIG_NETFILTER_FP_SMB"
+# fi
+# if [ "$CONFIG_FIRMWARE_INCLUDE_NFSD" != "y" -a "$CONFIG_FIRMWARE_INCLUDE_NFSC" != "y" -a "$CONFIG_FIRMWARE_INCLUDE_CIFS" != "y" ] ; then
+# 	func_disable_kernel_param "CONFIG_NETWORK_FILESYSTEMS"
+# 	if [ "$CONFIG_FIRMWARE_ENABLE_USB" != "y" ] || [ -z "$CONFIG_USB_SUPPORT" ] ; then
+# 		func_disable_kernel_param "CONFIG_NLS"
+# 		func_disable_kernel_param "CONFIG_LBDAF"
+# 	fi
+# fi
 ############################# USB AUDIO ###############################
-if [ "$CONFIG_FIRMWARE_INCLUDE_AUDIO" != "y" ] || [ "$CONFIG_FIRMWARE_ENABLE_USB" != "y" ] || [ -z "$CONFIG_USB_SUPPORT" ] ; then
-	func_disable_kernel_param "CONFIG_FW_LOADER"
-	func_disable_kernel_param "CONFIG_SOUND"
-fi
+# if [ "$CONFIG_FIRMWARE_INCLUDE_AUDIO" != "y" ] || [ "$CONFIG_FIRMWARE_ENABLE_USB" != "y" ] || [ -z "$CONFIG_USB_SUPPORT" ] ; then
+# 	func_disable_kernel_param "CONFIG_FW_LOADER"
+# 	func_disable_kernel_param "CONFIG_SOUND"
+# fi
 #######################################################################
+if [ "$CONFIG_WITHOUT_KERNEL" != "y" ] ; then
 echo --------------------------MAKE-DEP--------------------------------
 make dep
+fi
+if [ "$2" != "kmod" ] ; then
 echo --------------------------MAKE-ALL--------------------------------
 make
+fi
diff --git a/trunk/build_firmware_modify b/trunk/build_firmware_modify
--- a/trunk/build_firmware_modify
+++ b/trunk/build_firmware_modify
@@ -1,11 +1,13 @@
 #!/bin/bash
 
 if [ -z "$1" ] || [ "$EUID" != 0 ]; then
-	echo "Please run 'fakeroot $0 PRODUCT_NAME' to start build (see 'configs/templates/') " && exit 1
+	echo "Please run 'fakeroot $0 PRODUCT_NAME' to start build (see 'configs/templates/')"
+	echo "For Windows Subsystem for Linux(WSL), use 'fakeroot-tcp' instead of 'fakeroot', or run with sudo"
+	exit 1
 fi
-if [ -z "$2" ];then
+
 if [ ! -f configs/templates/$1.config ] ; then
-	echo "configs/templates/$1.config not found "
+	echo "configs/templates/$1.config not found!"
 	exit 1
 fi
 
@@ -30,40 +32,11 @@ echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n" >> .config #锐捷认证插件，选�
 echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> .config
 ##锐捷认证##
 
-##广告管理##
-echo "CONFIG_FIRMWARE_INCLUDE_ADBYBY=n" >> .config #adbyby plus+
-echo "CONFIG_FIRMWARE_INCLUDE_KOOLPROXY=n" >> .config #KP广告过滤
-##广告管理##
-
-##DNS服务##
-echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=n" >> .config #smartdns
-echo "CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=n" >> .config #adg DNS去AD
-
-##DNS服务##
-
-##文件管理##
-echo "CONFIG_FIRMWARE_INCLUDE_CADDY=n" >> .config #在线文件管理服务
-echo "CONFIG_FIRMWARE_INCLUDE_CADDYBIN=n" >> .config #集成caddu执行文件，此文件有13M,请注意固件大小。如果不集成，会从网上下载下来执行，不影响正常使用
-##文件管理##
-
-##音乐解锁##
-echo "CONFIG_FIRMWARE_INCLUDE_WYY=n" >> .config #网易云解锁
-echo "CONFIG_FIRMWARE_INCLUDE_WYYBIN=n" >> .config #网易云解锁GO版本执行文件（2M多）注意固件超大小
-##音乐解锁##
-
-##CURL服务##
-echo "CONFIG_FIRMWARE_INCLUDE_CURL=y" >> .config #CURL control. ~0.1MB
-##CURL服务##
-
-##内网穿透服务##
+##内网穿透##
 echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=n" >> .config #zerotier ~1.3M
-echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=n" >> .config #aliddns
-##内网穿透服务##
+echo "CONFIG_FIRMWARE_INCLUDE_NPS=n" >> .config #nps ~0.8M
+##内网穿透证##
 
-
-CONFIG_FIRMWARE_INCLUDE_CURL=y
-fi
-sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
 ROOTDIR=`pwd`
 export ROOTDIR=$ROOTDIR
 
@@ -106,21 +79,14 @@ func_disable_busybox_param()
 		sed -i "s/$1=y/\# $1 is not set/" $busybox_tf
 	fi
 }
-
-if [ ! -f "$ROOTDIR/.config" ] ; then
-	cp -fv "$ROOTDIR/configs/templates/n56u_dlna.config" "$ROOTDIR/.config"
-fi
-
-if [ ! -f "$ROOTDIR/.config" ] ; then
-	echo "Project config file .config not found! Terminate."
-	exit 1
-fi
+. $ROOTDIR/toolchain.inc
+echo "CONFIG_TOOLCHAIN_DIR=${CONFIG_TOOLCHAIN_DIR}" >> .config
 
 # load project root config
 . $ROOTDIR/.config
 
-if [ ! -f "$ROOTDIR/vendors/Ralink/$CONFIG_PRODUCT/config.arch" ] ; then
-	echo "Project product dir ($CONFIG_PRODUCT) not found! Terminate."
+if [ ! -f "$ROOTDIR/vendors/Ralink/config.arch" ] ; then
+	echo "Project product dir not found! Terminate."
 	exit 1
 fi
 
@@ -133,10 +99,6 @@ board_h="$ROOTDIR/configs/boards/$CONFIG_FIRMWARE_PRODUCT_ID/board.h"
 board_mk="$ROOTDIR/configs/boards/$CONFIG_FIRMWARE_PRODUCT_ID/board.mk"
 kernel_cd="$ROOTDIR/configs/boards/$CONFIG_FIRMWARE_PRODUCT_ID"
 kernel_tf="$ROOTDIR/$CONFIG_LINUXDIR/.config"
-
-if [ "$CONFIG_LINUXDIR" = "linux-3.0.x" ] ; then
-	kernel_id="3.0.x"
-fi
 
 if [ "$CONFIG_FIRMWARE_TYPE_ROOTFS_IN_RAM" = "y" ] ; then
 	kernel_cf="${kernel_cd}/kernel-${kernel_id}.ram.config"
@@ -176,7 +138,7 @@ mkdir -p $ROOTDIR/images
 
 echo --------------------------COPY-CONFIG-----------------------------
 ######################### FOR-ALL-DEVICES #############################
-ln -sf vendors/Ralink/$CONFIG_PRODUCT/config.arch config.arch
+ln -sf vendors/Ralink/config.arch config.arch
 cp -fL "$kernel_cf" "$kernel_tf"
 cp -fL "$busybox_cf" "$busybox_tf"
 cp -fL "$board_mk" "$ROOTDIR/user/shared/board.mk"
@@ -195,11 +157,14 @@ rm -rf "$dir_wifi_dst/mt76x2"
 rm -rf "$dir_wifi_dst/mt76x3"
 rm -rf "$dir_wifi_dst/mt7628"
 rm -rf "$dir_wifi_dst/mt7615"
+rm -rf "$dir_wifi_dst/mt7915"
 
 mkdir -p "$dir_wifi_dst/mt76x3"
 cp -f "$dir_wifi_src/rtpci/4.1.X.X/mt76x3/Kconfig" "$dir_wifi_dst/mt76x3/Kconfig"
 mkdir -p "$dir_wifi_dst/mt7615/embedded"
-cp -f "$dir_wifi_src/rtpci/4.4.2.1/mt7615/embedded/Kconfig" "$dir_wifi_dst/mt7615/embedded/Kconfig"
+cp -f "$dir_wifi_src/rtpci/5.0.5.1/mt7615/embedded/Kconfig" "$dir_wifi_dst/mt7615/embedded/Kconfig"
+mkdir -p "$dir_wifi_dst/mt7915/embedded"
+cp -f "$dir_wifi_src/rtpci/7.3.0.1/mt7915/embedded/Kconfig" "$dir_wifi_dst/mt7915/embedded/Kconfig"
 
 if [ -n "$CONFIG_RT2860V2_AP" ] ; then
 	dir_wifi_ver="2.7.X.X"
@@ -260,9 +225,6 @@ if [ -n "$CONFIG_MT76X2_AP" ] ; then
 fi
 if [ -n "$CONFIG_MT76X3_AP" ] ; then
 	dir_wifi_ver="4.1.X.X"
-	if [ "$CONFIG_FIRMWARE_WIFI2_DRIVER" = "4.1.0.0" ]; then
-		dir_wifi_ver="4.1.0.0"
-	fi
 	cp -rfL "$dir_wifi_src/rtpci/$dir_wifi_ver/mt76x3" "$dir_wifi_dst/"
 	cp -rfL "$dir_wifi_src/rtpci/$dir_wifi_ver/mt76x3_ap" "$dir_wifi_dst/"
 fi
@@ -272,15 +234,19 @@ if [ -n "$CONFIG_MT7628_AP" ] ; then
 	cp -rfL "$dir_wifi_src/rtsoc/$dir_wifi_ver/mt7628_ap" "$dir_wifi_dst/"
 fi
 if [ -n "$CONFIG_MT7615_AP" ] ; then
-	dir_wifi_ver="4.4.2.1"
-	if [ "$CONFIG_FIRMWARE_WIFI_DRIVER" = "5.0.3.0" ] || [ "$CONFIG_FIRMWARE_WIFI2_DRIVER" = "5.0.3.0" ] || [ "$CONFIG_FIRMWARE_WIFI5_DRIVER" = "5.0.3.0" ]; then
-		dir_wifi_ver="5.0.3.0"
-	fi
-	if [ "$CONFIG_FIRMWARE_WIFI_DRIVER" = "5.0.4.0" ] || [ "$CONFIG_FIRMWARE_WIFI2_DRIVER" = "5.0.4.0" ] || [ "$CONFIG_FIRMWARE_WIFI5_DRIVER" = "5.0.4.0" ]; then
-		dir_wifi_ver="5.0.4.0"
+	dir_wifi_ver="5.0.5.1"
+	if [ "$CONFIG_FIRMWARE_WIFI_DRIVER" = "4.4.2.1" ] || \
+		[ "$CONFIG_FIRMWARE_WIFI2_DRIVER" = "4.4.2.1" ] || \
+		[ "$CONFIG_FIRMWARE_WIFI5_DRIVER" = "4.4.2.1" ]; then
+		dir_wifi_ver="4.4.2.1"
 	fi
 	cp -rfL "$dir_wifi_src/rtpci/$dir_wifi_ver/mt7615" "$dir_wifi_dst/"
 	cp -rfL "$dir_wifi_src/rtpci/$dir_wifi_ver/mt7615_ap" "$dir_wifi_dst/"
+fi
+if [ -n "$CONFIG_MT7915_AP" ] ; then
+	dir_wifi_ver="7.3.0.1"
+	cp -rfL "$dir_wifi_src/rtpci/$dir_wifi_ver/mt7915" "$dir_wifi_dst/"
+	cp -rfL "$dir_wifi_src/rtpci/$dir_wifi_ver/mt7915_ap" "$dir_wifi_dst/"
 fi
 ############################ HWNAT ####################################
 dir_ppe_src="$ROOTDIR/proprietary/rt_ppe"
@@ -348,39 +314,15 @@ fi
 #SFE
 if [ "$CONFIG_FIRMWARE_INCLUDE_SFE" = "y" ] ; then
 	func_enable_kernel_param "CONFIG_SHORTCUT_FE"
+	func_enable_kernel_param "CONFIG_NF_CONNTRACK_EVENTS"
+	func_enable_kernel_param "CONFIG_NF_CONNTRACK_CHAIN_EVENTS"
 else
 	func_disable_kernel_param "CONFIG_SHORTCUT_FE"
+	func_disable_kernel_param "CONFIG_NF_CONNTRACK_EVENTS"
+	func_disable_kernel_param "CONFIG_NF_CONNTRACK_CHAIN_EVENTS"
 fi
 ############################# USB #####################################
 if [ "$CONFIG_FIRMWARE_ENABLE_USB" != "y" ] || [ -z "$CONFIG_USB_SUPPORT" ] ; then
-# 	func_disable_kernel_param "CONFIG_SWAP"
-# 	func_disable_kernel_param "CONFIG_FAT_FS"
-# 	func_disable_kernel_param "CONFIG_MSDOS_FS"
-# 	func_disable_kernel_param "CONFIG_VFAT_FS"
-# 	func_disable_kernel_param "CONFIG_UFSD_FS"
-# 	func_disable_kernel_param "CONFIG_EXFAT_FS"
-# 	func_disable_kernel_param "CONFIG_EXT2_FS"
-# 	func_disable_kernel_param "CONFIG_EXT3_FS"
-# 	func_disable_kernel_param "CONFIG_EXT4_FS"
-# 	func_disable_kernel_param "CONFIG_JBD"
-# 	func_disable_kernel_param "CONFIG_JBD2"
-# 	func_disable_kernel_param "CONFIG_XFS_FS"
-# 	func_disable_kernel_param "CONFIG_FUSE_FS"
-# 	func_disable_kernel_param "CONFIG_FSCACHE"
-# 	func_disable_kernel_param "CONFIG_INOTIFY_USER"
-# 	func_disable_kernel_param "CONFIG_NFSD"
-# 	func_disable_kernel_param "CONFIG_PARTITION_ADVANCED"
-# 	func_disable_kernel_param "CONFIG_NLS_CODEPAGE_866"
-# 	func_disable_kernel_param "CONFIG_NLS_ISO8859_1"
-# 	func_disable_kernel_param "CONFIG_SCSI"
-# 	func_disable_kernel_param "CONFIG_SCSI_MOD"
-# 	func_disable_kernel_param "CONFIG_INPUT"
-# 	func_disable_kernel_param "CONFIG_USB_SUPPORT"
-# 	func_disable_kernel_param "CONFIG_HID_SUPPORT"
-# 	func_disable_kernel_param "CONFIG_MEDIA_SUPPORT"
-# 	func_disable_kernel_param "CONFIG_CRC16"
-# 	func_disable_kernel_param "CONFIG_NETFILTER_FP_SMB"
-# 	func_disable_kernel_param "CONFIG_RT3XXX_EHCI_OHCI"
 	func_disable_busybox_param "CONFIG_FDISK"
 	func_disable_busybox_param "CONFIG_FEATURE_FDISK_WRITABLE"
 	func_disable_busybox_param "CONFIG_FEATURE_FDISK_ADVANCED"
@@ -396,11 +338,6 @@ if [ "$CONFIG_FIRMWARE_ENABLE_USB" != "y" ] || [ -z "$CONFIG_USB_SUPPORT" ] ; th
 	func_disable_busybox_param "CONFIG_FEATURE_VOLUMEID_EXT"
 	func_disable_busybox_param "CONFIG_FEATURE_VOLUMEID_XFS"
 	func_disable_busybox_param "CONFIG_FEATURE_VOLUMEID_LINUXSWAP"
-#	if [ "$CONFIG_FIRMWARE_INCLUDE_OPENVPN" != "y" ] ; then
-#		func_disable_kernel_param "CONFIG_TUN"
-#		func_disable_kernel_param "CONFIG_HOTPLUG"
-#	fi
-	CONFIG_FIRMWARE_INCLUDE_NFSD=n
 else
 ############################# UFSD ####################################
 if [ "$CONFIG_FIRMWARE_ENABLE_UFSD" != "y" ] ; then
